export { default as NavBar } from "./NavBar/NavBar";
export { default as Home } from "./Home/Home";
export { default as TPOne } from "./TPOne/TPOne";
export { default as ABR } from "./ABR/ABR";
export { default as AVL } from "./AVL/AVL";
export { default as TASMIN } from "./TASMIN/TASMIN";
export {default as TASMAX} from "./TASMAX/TASMAX";
export { default as AMR } from "./AMR/AMR";
export { default as GrapheNonOr } from "./GrapheNonOr/GrapheNonOr";
export { default as GrapheOriente } from "./GrapheOriente/GrapheOriente";
export {default as GraphePondere} from "./Graphepondere/Graphepondere";
export {default as HomePageOfTPOne} from "./HomePageOfTPOne/HomePageOfTPOne";
export { default as GrapheNonPondere } from "./GrapheNonPondere/GrapheNonPondere";
export { default as B_ARBER } from "./B_ARBER/B_ARBER";